/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package learnGUI;

import Main_Class.centroDeEventos;
import Main_Class.evento;
import Main_Class.utilizador;
import java.util.List;

/**
 *
 * @author JASM
 */
public class testeImpressao extends javax.swing.JFrame {
    
    /**
     * Creates new form testeImpressao
     */
    private final centroDeEventos ce;
    
    /**
     *
     * @param ce
     */
    public testeImpressao(centroDeEventos ce) {
        this.ce=ce;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoImpressaoUtilizadores = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botaoImpressaoEventos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        botaoImpressaoUtilizadores.setText("IU");
        botaoImpressaoUtilizadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoImpressaoUtilizadoresActionPerformed(evt);
            }
        });

        jLabel1.setText("Impressao de Utilizadores");

        botaoImpressaoEventos.setText("IE");
        botaoImpressaoEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoImpressaoEventosActionPerformed(evt);
            }
        });

        jLabel2.setText("Impressao de Eventos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoImpressaoEventos)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoImpressaoUtilizadores)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoImpressaoUtilizadores)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoImpressaoEventos)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoImpressaoEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoImpressaoEventosActionPerformed
        List<evento> event = ce.getListaEvento();
        for (evento e : event) {
            System.out.println(e.toStringComFaeOrganizador());
        }
    }//GEN-LAST:event_botaoImpressaoEventosActionPerformed

    private void botaoImpressaoUtilizadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoImpressaoUtilizadoresActionPerformed
        List<utilizador> utili = ce.getListaUtilizadores();
        for (int i = 0; i < utili.size(); i++) {
            System.out.println(i + " " + utili.get(i).toString());
        }
    }//GEN-LAST:event_botaoImpressaoUtilizadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testeImpressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testeImpressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testeImpressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testeImpressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(centroDeEventos ce) {
                new testeImpressao(ce).setVisible(true);
            }

            @Override
            public void run() {
                System.out.println("o");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoImpressaoEventos;
    private javax.swing.JButton botaoImpressaoUtilizadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
