/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package learnGUI;

import Controller.atribuirCandidaturaController;
import Main_Class.algoritmoAtribuicao;
import Main_Class.atribuicao;
import Main_Class.candidatura;
import Main_Class.centroDeEventos;
import Main_Class.evento;
import Main_Class.fae;
import Main_Class.organizador;
import Utils_Consola.utilitariosConsola;
import java.awt.Dimension;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.*;

/**
 *
 * @author JASM
 */
public class testeAtribuirCandidatura extends javax.swing.JFrame {

    private final centroDeEventos ce;
    private final atribuirCandidaturaController atribuirController;
    private List<fae> listaFAEdoEvento;
    private List<organizador> listaOrganizador;
    private List<candidatura> listaCandidaturasEvento;
    private List<evento> ListaEventosOrganizadorDataSubmissaoFinalizada;
    private List<algoritmoAtribuicao> ListaAlgoritmos;
    private List<atribuicao> atribuicaoTEMP;
    private algoritmoAtribuicao alg;
    private organizador org;
    private List listaAtribuicoesEvento;
    /**
     * Creates new form testeAtribuirCandidatura
     */
    public testeAtribuirCandidatura(centroDeEventos ce) {
        this.ce = ce;
        atribuirController = new atribuirCandidaturaController(ce);
        initComponents();
        setResizable(false);
        jListFAEDoEvento.setVisible(false);
        jListCandidaturasDoEvento.setVisible(false);
        jListaEventosDataSubmissaoCaducada.setVisible(false);
        botaoConfirmaEvento.setEnabled(false);
        botaoConfirmaOrganizador.setEnabled(false);
        botaoEmparelhar.setEnabled(false);
        botaoSubmeter.setEnabled(false);
        jListAlgoritmos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListaEventosDataSubmissaoCaducada = new javax.swing.JList<>();
        labelTitulo = new javax.swing.JLabel();
        labelDescricao = new javax.swing.JLabel();
        labelLocal = new javax.swing.JLabel();
        labelDataInicio = new javax.swing.JLabel();
        labelDataFinal = new javax.swing.JLabel();
        descritivoTitulo = new javax.swing.JLabel();
        descritivoDescricao = new javax.swing.JLabel();
        descritivoLocal = new javax.swing.JLabel();
        descritivoDataInicio = new javax.swing.JLabel();
        descritivoDataFim = new javax.swing.JLabel();
        botaoConfirmaEvento = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        painelFAE = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListFAEDoEvento = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListCandidaturasDoEvento = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jListAlgoritmos = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        descritivoAlgoritmos = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        descritivoNome = new javax.swing.JLabel();
        descritivoEmail = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListOrganizador = new javax.swing.JList<>();
        botaoConfirmaOrganizador = new javax.swing.JButton();
        botaoEmparelhar = new javax.swing.JButton();
        botaoSubmeter = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableEmparelhamentoFAECandidatura = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        botaoSair = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UC3 - Atribuir Candidatura");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Escolha o Evento"));

        jListaEventosDataSubmissaoCaducada.setMaximumSize(new java.awt.Dimension(0, 130));
        jListaEventosDataSubmissaoCaducada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListaEventosDataSubmissaoCaducadaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListaEventosDataSubmissaoCaducada);

        labelTitulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTitulo.setText("Titulo");

        labelDescricao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelDescricao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDescricao.setText("Descrição");

        labelLocal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelLocal.setText("Local");

        labelDataInicio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelDataInicio.setText("Data Inicio");

        labelDataFinal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelDataFinal.setText("Data Final");

        botaoConfirmaEvento.setText("Confirma Evento");
        botaoConfirmaEvento.setMaximumSize(new java.awt.Dimension(123, 10));
        botaoConfirmaEvento.setMinimumSize(new java.awt.Dimension(123, 10));
        botaoConfirmaEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoConfirmaEventoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelDataFinal)
                            .addComponent(labelLocal)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labelDescricao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelDataInicio))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descritivoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descritivoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descritivoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descritivoDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descritivoDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(botaoConfirmaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTitulo)
                            .addComponent(descritivoTitulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDescricao)
                            .addComponent(descritivoDescricao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelLocal)
                            .addComponent(descritivoLocal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDataInicio)
                            .addComponent(descritivoDataInicio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDataFinal)
                            .addComponent(descritivoDataFim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoConfirmaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("FAE do Evento"));
        jScrollPane2.setViewportView(jListFAEDoEvento);

        jScrollPane5.setBorder(javax.swing.BorderFactory.createTitledBorder("Candidaturas do Evento"));
        jScrollPane5.setViewportView(jListCandidaturasDoEvento);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Algoritmos"));

        jListAlgoritmos.setEnabled(false);
        jListAlgoritmos.setToolTipText("");
        jListAlgoritmos.setMaximumSize(new java.awt.Dimension(47, 120));
        jListAlgoritmos.setMinimumSize(new java.awt.Dimension(47, 120));
        jListAlgoritmos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListAlgoritmosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jListAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jListAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Descricao"));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descritivoAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(descritivoAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelFAELayout = new javax.swing.GroupLayout(painelFAE);
        painelFAE.setLayout(painelFAELayout);
        painelFAELayout.setHorizontalGroup(
            painelFAELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFAELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelFAELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelFAELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelFAELayout.setVerticalGroup(
            painelFAELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFAELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelFAELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(painelFAELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(painelFAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Escolha o Organizador"));

        labelNome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelNome.setText("Nome");

        labelEmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelEmail.setText("E-mail");

        listaOrganizador = atribuirController.getListaOrganizadorUnicosComEventosComDataSubmissaoCaducada();
        String[] stringsOrganizador = new String[listaOrganizador.size()];
        int i=0;
        for (organizador o: listaOrganizador){
            stringsOrganizador[i]=o.getUser().getNome();
            i++;
        }
        jListOrganizador.setModel(new javax.swing.AbstractListModel<String>() {

            public int getSize() { return stringsOrganizador.length; }
            public String getElementAt(int i) { return stringsOrganizador[i]; }
        });
        jListOrganizador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListOrganizadorMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jListOrganizador);

        botaoConfirmaOrganizador.setText("Confirma Organizador");
        botaoConfirmaOrganizador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoConfirmaOrganizadorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNome)
                            .addComponent(labelEmail))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descritivoEmail)
                            .addComponent(descritivoNome)))
                    .addComponent(botaoConfirmaOrganizador))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNome)
                            .addComponent(descritivoNome))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEmail)
                            .addComponent(descritivoEmail))
                        .addGap(18, 18, 18)
                        .addComponent(botaoConfirmaOrganizador, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoEmparelhar.setText("Emparelhar");
        botaoEmparelhar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoEmparelharMouseClicked(evt);
            }
        });

        botaoSubmeter.setText("Submeter");
        botaoSubmeter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoSubmeterMouseClicked(evt);
            }
        });
        botaoSubmeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSubmeterActionPerformed(evt);
            }
        });

        jTableEmparelhamentoFAECandidatura.getTableHeader().setReorderingAllowed(false);
        jScrollPane8.setViewportView(jTableEmparelhamentoFAECandidatura);

        jLabel8.setText("Emparelhamento");

        botaoSair.setText("Sair");
        botaoSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(botaoEmparelhar))
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoSubmeter)
                            .addComponent(botaoSair))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(botaoEmparelhar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(botaoSubmeter)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(botaoSair))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListaEventosDataSubmissaoCaducadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListaEventosDataSubmissaoCaducadaMouseClicked
        System.out.println(jListaEventosDataSubmissaoCaducada.getSelectedIndex());
        evento e = ListaEventosOrganizadorDataSubmissaoFinalizada.get(jListaEventosDataSubmissaoCaducada.getSelectedIndex());
        descritivoTitulo.setText(e.getTitulo());
        descritivoDescricao.setText(e.getTextoDescritivo());
        descritivoLocal.setText(e.getLocal());
        descritivoDataInicio.setText(e.getDataInicio().toString());
        descritivoDataFim.setText(e.getDataFim().toString());
        listaFAEdoEvento = atribuirController.getListaFAE(e);
        botaoConfirmaOrganizador.setEnabled(false);
        botaoConfirmaEvento.setEnabled(true);
    }//GEN-LAST:event_jListaEventosDataSubmissaoCaducadaMouseClicked

    private void jListOrganizadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListOrganizadorMouseClicked
        org = listaOrganizador.get(jListOrganizador.getSelectedIndex());
        descritivoNome.setText(org.getUser().getNome());
        descritivoEmail.setText(org.getUser().getEmail());
        botaoConfirmaOrganizador.setEnabled(true);
    }//GEN-LAST:event_jListOrganizadorMouseClicked

    private void botaoConfirmaOrganizadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConfirmaOrganizadorMouseClicked
        org = listaOrganizador.get(jListOrganizador.getSelectedIndex());
        ListaEventosOrganizadorDataSubmissaoFinalizada = atribuirController.getListaEventosOrganizadorDataSubmissaoFinalizada(org);
        if (ListaEventosOrganizadorDataSubmissaoFinalizada.size() == 0) {
            JOptionPane.showMessageDialog(null, "O " + org.getUser().getNome() + " nao tem eventos associados", "Informacao", JOptionPane.INFORMATION_MESSAGE);
        } else {
            DefaultListModel dlmjleventos = new DefaultListModel();
            jListaEventosDataSubmissaoCaducada.setModel(dlmjleventos);
            for (evento e : ListaEventosOrganizadorDataSubmissaoFinalizada) {
                dlmjleventos.addElement(e.getTitulo());
            }
            jListOrganizador.setEnabled(false);
            jListaEventosDataSubmissaoCaducada.setVisible(true);
        }
    }//GEN-LAST:event_botaoConfirmaOrganizadorMouseClicked

    private void botaoConfirmaEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConfirmaEventoMouseClicked
        evento e = ListaEventosOrganizadorDataSubmissaoFinalizada.get(jListaEventosDataSubmissaoCaducada.getSelectedIndex());
        listaFAEdoEvento = atribuirController.getListaFAE(e);
        DefaultListModel dlmJLFAE = new DefaultListModel();
        jListFAEDoEvento.setModel(dlmJLFAE);
        for (fae f : listaFAEdoEvento) {
            dlmJLFAE.addElement(f.getUser().getNome());
        }
        listaCandidaturasEvento = atribuirController.getListaCandidatura(e);
        DefaultListModel dlmJLCandidaturasEvento = new DefaultListModel();
        jListCandidaturasDoEvento.setModel(dlmJLCandidaturasEvento);
        for (candidatura c : listaCandidaturasEvento) {
            dlmJLCandidaturasEvento.addElement(c.getNomeEmpresa());
        }
        ce.getAlgoritmosAtribuicao();
        ListaAlgoritmos = atribuirController.getAlgoritmosAtribuicao();
        DefaultListModel dlmJLalgoritmos = new DefaultListModel();
        jListAlgoritmos.setModel(dlmJLalgoritmos);
        for (algoritmoAtribuicao alg : ListaAlgoritmos) {
            dlmJLalgoritmos.addElement(alg.getNome());
        }
        jListAlgoritmos.setVisible(true);
        jListAlgoritmos.setEnabled(true);
        jListaEventosDataSubmissaoCaducada.setEnabled(false);
        jListFAEDoEvento.setVisible(true);
        jListCandidaturasDoEvento.setVisible(true);
        botaoConfirmaEvento.setEnabled(false);
    }//GEN-LAST:event_botaoConfirmaEventoMouseClicked

    private void jListAlgoritmosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListAlgoritmosMouseClicked
        algoritmoAtribuicao alg = ListaAlgoritmos.get(jListAlgoritmos.getSelectedIndex());
        descritivoAlgoritmos.setMaximumSize(new Dimension(250,100));
        descritivoAlgoritmos.setText(alg.getDescritivo());
        botaoEmparelhar.setEnabled(true);

    }//GEN-LAST:event_jListAlgoritmosMouseClicked

    private void botaoEmparelharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEmparelharMouseClicked
        evento e = ListaEventosOrganizadorDataSubmissaoFinalizada.get(jListaEventosDataSubmissaoCaducada.getSelectedIndex());
        listaAtribuicoesEvento = atribuirController.getListaAtribuicoes(e);
        listaAtribuicoesEvento.clear();
        alg = ListaAlgoritmos.get(jListAlgoritmos.getSelectedIndex());
        atribuicaoTEMP = alg.runAlgoritmo(listaFAEdoEvento, listaCandidaturasEvento, listaAtribuicoesEvento);
        String[] columns = {"FAE","Candidatura/Empresa"};
        DefaultTableModel dtmEmparelhamento = new DefaultTableModel(columns,2);
        dtmEmparelhamento.setNumRows(atribuicaoTEMP.size());
        int i =0;
        for (atribuicao atri : atribuicaoTEMP) {
            String faeAtribuido=(atri.getFae().toStringUsername());
            dtmEmparelhamento.setValueAt(faeAtribuido, i, 0);
            String candAtribuido = (atri.getCandidatura().getNomeEmpresa());
            dtmEmparelhamento.setValueAt(candAtribuido, i, 1);
            i++;
        }
        jTableEmparelhamentoFAECandidatura.setModel(dtmEmparelhamento);
        botaoSubmeter.setEnabled(true);
    }//GEN-LAST:event_botaoEmparelharMouseClicked

    private void botaoSubmeterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSubmeterMouseClicked
        if (JOptionPane.showConfirmDialog(null, "Foi gerado com sucesso o seguinte emparelhamento\n" + listaAtribuicoesEvento.toString() + "\n\nConfirma?", "Confirmação dos dados",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.setVisible(false);
        
        if (listaAtribuicoesEvento.size() == atribuicaoTEMP.size()) {;
            listaAtribuicoesEvento.addAll(atribuicaoTEMP);
        }
        }
    }//GEN-LAST:event_botaoSubmeterMouseClicked

    private void botaoSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSairMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_botaoSairMouseClicked

    private void botaoSubmeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSubmeterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSubmeterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testeAtribuirCandidatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testeAtribuirCandidatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testeAtribuirCandidatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testeAtribuirCandidatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(centroDeEventos ce) {
                new testeAtribuirCandidatura(ce).setVisible(true);
            }

            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConfirmaEvento;
    private javax.swing.JButton botaoConfirmaOrganizador;
    private javax.swing.JButton botaoEmparelhar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoSubmeter;
    private javax.swing.JLabel descritivoAlgoritmos;
    private javax.swing.JLabel descritivoDataFim;
    private javax.swing.JLabel descritivoDataInicio;
    private javax.swing.JLabel descritivoDescricao;
    private javax.swing.JLabel descritivoEmail;
    private javax.swing.JLabel descritivoLocal;
    private javax.swing.JLabel descritivoNome;
    private javax.swing.JLabel descritivoTitulo;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jListAlgoritmos;
    private javax.swing.JList<String> jListCandidaturasDoEvento;
    private javax.swing.JList<String> jListFAEDoEvento;
    private javax.swing.JList<String> jListOrganizador;
    private javax.swing.JList<String> jListaEventosDataSubmissaoCaducada;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableEmparelhamentoFAECandidatura;
    private javax.swing.JLabel labelDataFinal;
    private javax.swing.JLabel labelDataInicio;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelLocal;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel painelFAE;
    // End of variables declaration//GEN-END:variables
}
